after_success:
  - npm install -g firebase-tools
  - firebase deploy --token $FIREBASE_TOKEN --non-interactive
before_install:
  - cd src
cache:
  directories:
    - node_modules
language: node_js
node_js:
  - stable
script:
  - npm test
  - CI=false npm run build
